;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                                        ;
;                                       COMMON.INC                                       ;
;                         Contains common constants for all files                        ;
;                                      Tim Menninger                                     ;
;                                                                                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;	

;
; Description:		This file contains the struct definition for queues and constants.
;
; Revision History:
;       09/20/16    Tim Menninger   Created
;

TRUE                EQU     1
FALSE               EQU     0